
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package testAnalisis;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 4;
  public static final int POR = 5;
  public static final int ENTRE = 6;
  public static final int EOF = 0;
  public static final int MAS = 3;
  public static final int NUMERO = 12;
  public static final int ASIG = 10;
  public static final int ID = 11;
  public static final int error = 1;
  public static final int PRINT = 9;
  public static final int RPAREN = 8;
  public static final int PUNTOYCOMA = 2;
  public static final int LPAREN = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PUNTOYCOMA",
  "MAS",
  "MENOS",
  "POR",
  "ENTRE",
  "LPAREN",
  "RPAREN",
  "PRINT",
  "ASIG",
  "ID",
  "NUMERO"
  };
}

