// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: Lexer.jflex

package testAnalisis;

import java_cup.runtime.*;
import java.io.*;


@SuppressWarnings("fallthrough")
class Yylex implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\1\u0300\1\u0400\1\u0500\1\u0600\1\u0700"+
    "\1\u0800\1\u0900\1\u0a00\1\u0b00\1\u0c00\1\u0d00\1\u0e00\1\u0f00"+
    "\1\u1000\1\u0100\1\u1100\1\u1200\1\u1300\1\u0100\1\u1400\1\u1500"+
    "\1\u1600\1\u1700\1\u1800\1\u1900\1\u1a00\1\u1b00\1\u0100\1\u1c00"+
    "\1\u1d00\1\u1e00\12\u1f00\1\u2000\1\u2100\1\u2200\1\u1f00\1\u2300"+
    "\1\u2400\2\u1f00\31\u0100\1\u2500\126\u0100\1\u2600\1\u0100\1\u2700"+
    "\1\u2800\1\u2900\1\u2a00\1\u2b00\1\u2c00\53\u0100\1\u2d00\10\u2e00"+
    "\31\u1f00\1\u0100\1\u2f00\1\u3000\1\u0100\1\u3100\1\u3200\1\u3300"+
    "\1\u3400\1\u3500\1\u3600\1\u3700\1\u3800\1\u3900\1\u0100\1\u3a00"+
    "\1\u3b00\1\u3c00\1\u3d00\1\u3e00\1\u3f00\1\u4000\1\u4100\1\u4200"+
    "\1\u4300\1\u4400\1\u4500\1\u4600\1\u4700\1\u4800\1\u4900\1\u4a00"+
    "\1\u4b00\1\u4c00\1\u4d00\1\u1f00\1\u4e00\1\u4f00\1\u5000\1\u5100"+
    "\3\u0100\1\u5200\1\u5300\1\u5400\11\u1f00\1\u5500\4\u0100\1\u5600"+
    "\17\u1f00\2\u0100\1\u5700\41\u1f00\2\u0100\1\u5800\1\u5900\2\u1f00"+
    "\1\u5a00\1\u5b00\27\u0100\1\u5c00\4\u0100\1\u5d00\1\u5e00\41\u1f00"+
    "\1\u5f00\1\u0100\1\u6000\1\u6100\11\u1f00\1\u6200\22\u1f00\1\u6300"+
    "\1\u1f00\1\u6400\1\u6500\1\u1f00\1\u6600\1\u6700\1\u6800\1\u6900"+
    "\2\u1f00\1\u6a00\4\u1f00\1\u6b00\1\u6c00\1\u6d00\1\u6e00\1\u1f00"+
    "\1\u6f00\2\u1f00\1\u7000\1\u7100\1\u7200\2\u1f00\1\u7300\1\u1f00"+
    "\1\u7400\14\u1f00\1\u7500\4\u1f00\246\u0100\1\u7600\20\u0100\1\u7700"+
    "\1\u7800\25\u0100\1\u7900\34\u0100\1\u7a00\14\u1f00\2\u0100\1\u7b00"+
    "\5\u1f00\23\u0100\1\u7c00\17\u0100\1\u7d00\u0adc\u1f00\1\u7e00\1\u7f00"+
    "\u02fe\u1f00";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\2\1\2\2\1\1\16\0\4\3\1\1\3\3"+
    "\1\4\3\3\1\5\1\6\1\7\1\10\1\3\1\11"+
    "\1\3\1\12\12\13\1\3\1\14\1\3\1\15\3\3"+
    "\10\4\1\16\4\4\1\17\1\4\1\20\1\4\1\21"+
    "\1\4\1\22\6\4\1\3\1\23\2\3\1\4\1\3"+
    "\32\4\4\3\6\0\1\24\32\0\2\3\4\4\4\3"+
    "\1\4\2\3\1\0\7\3\1\4\4\3\1\4\5\3"+
    "\27\4\1\3\37\4\1\3\u01ca\4\4\3\14\4\16\3"+
    "\5\4\7\3\1\4\1\3\1\4\21\3\160\0\5\4"+
    "\1\3\2\4\2\3\4\4\1\3\1\4\6\3\1\4"+
    "\1\3\3\4\1\3\1\4\1\3\24\4\1\3\123\4"+
    "\1\3\213\4\1\3\5\0\2\3\246\4\1\3\46\4"+
    "\2\3\1\4\6\3\51\4\6\3\1\4\1\3\55\0"+
    "\1\3\1\0\1\3\2\0\1\3\2\0\1\3\1\0"+
    "\10\3\33\4\4\3\4\4\15\3\6\0\5\3\1\4"+
    "\4\3\13\0\1\3\1\0\3\3\53\4\37\0\4\3"+
    "\2\4\1\0\143\4\1\3\1\4\10\0\1\3\6\0"+
    "\2\4\2\0\1\3\4\0\2\4\12\0\3\4\2\3"+
    "\1\4\17\3\1\0\1\4\1\0\36\4\33\0\2\3"+
    "\131\4\13\0\1\4\16\3\12\0\41\4\11\0\2\4"+
    "\4\3\1\4\2\3\1\0\30\4\4\0\1\4\11\0"+
    "\1\4\3\0\1\4\5\0\22\3\31\4\3\0\4\3"+
    "\13\4\5\3\30\4\1\3\6\4\1\3\2\0\6\3"+
    "\10\0\52\4\72\0\66\4\3\0\1\4\22\0\1\4"+
    "\7\0\12\4\2\0\2\3\12\0\1\3\20\4\3\0"+
    "\1\3\10\4\2\3\2\4\2\3\26\4\1\3\7\4"+
    "\1\3\1\4\3\3\4\4\2\3\1\0\1\4\7\0"+
    "\2\3\2\0\2\3\3\0\1\4\10\3\1\0\4\3"+
    "\2\4\1\3\3\4\2\0\2\3\12\0\4\4\7\3"+
    "\2\4\1\3\1\0\2\3\3\0\1\3\6\4\4\3"+
    "\2\4\2\3\26\4\1\3\7\4\1\3\2\4\1\3"+
    "\2\4\1\3\2\4\2\3\1\0\1\3\5\0\4\3"+
    "\2\0\2\3\3\0\3\3\1\0\7\3\4\4\1\3"+
    "\1\4\7\3\14\0\3\4\1\0\13\3\3\0\1\3"+
    "\11\4\1\3\3\4\1\3\26\4\1\3\7\4\1\3"+
    "\2\4\1\3\5\4\2\3\1\0\1\4\10\0\1\3"+
    "\3\0\1\3\3\0\2\3\1\4\17\3\2\4\2\0"+
    "\2\3\12\0\1\3\1\4\7\3\1\4\6\0\1\3"+
    "\3\0\1\3\10\4\2\3\2\4\2\3\26\4\1\3"+
    "\7\4\1\3\2\4\1\3\5\4\2\3\1\0\1\4"+
    "\7\0\2\3\2\0\2\3\3\0\7\3\3\0\4\3"+
    "\2\4\1\3\3\4\2\0\2\3\12\0\1\3\1\4"+
    "\20\3\1\0\1\4\1\3\6\4\3\3\3\4\1\3"+
    "\4\4\3\3\2\4\1\3\1\4\1\3\2\4\3\3"+
    "\2\4\3\3\3\4\3\3\14\4\4\3\5\0\3\3"+
    "\3\0\1\3\4\0\2\3\1\4\6\3\1\0\16\3"+
    "\12\0\11\3\1\4\6\3\5\0\10\4\1\3\3\4"+
    "\1\3\27\4\1\3\20\4\2\3\1\0\1\4\7\0"+
    "\1\3\3\0\1\3\4\0\7\3\2\0\1\3\3\4"+
    "\2\3\1\4\2\3\2\4\2\0\2\3\12\0\20\3"+
    "\1\4\3\0\1\3\10\4\1\3\3\4\1\3\27\4"+
    "\1\3\12\4\1\3\5\4\2\3\1\0\1\4\7\0"+
    "\1\3\3\0\1\3\4\0\7\3\2\0\6\3\2\4"+
    "\1\3\2\4\2\0\2\3\12\0\1\3\2\4\1\0"+
    "\14\3\4\0\11\4\1\3\3\4\1\3\51\4\2\0"+
    "\1\4\7\0\1\3\3\0\1\3\4\0\1\4\5\3"+
    "\3\4\1\0\7\3\3\4\2\0\2\3\12\0\12\3"+
    "\6\4\1\3\3\0\1\3\22\4\3\3\30\4\1\3"+
    "\11\4\1\3\1\4\2\3\7\4\3\3\1\0\4\3"+
    "\6\0\1\3\1\0\1\3\10\0\6\3\12\0\2\3"+
    "\2\0\15\3\60\4\1\0\2\4\7\0\4\3\10\4"+
    "\10\0\1\3\12\0\47\3\2\4\1\3\1\4\1\3"+
    "\5\4\1\3\30\4\1\3\1\4\1\3\12\4\1\0"+
    "\2\4\11\0\1\4\2\3\5\4\1\3\1\4\1\3"+
    "\7\0\1\3\12\0\2\3\4\4\40\3\1\4\27\3"+
    "\2\0\6\3\12\0\13\3\1\0\1\3\1\0\1\3"+
    "\1\0\4\3\2\0\10\4\1\3\44\4\4\3\24\0"+
    "\1\3\2\0\5\4\13\0\1\3\44\0\11\3\1\0"+
    "\71\3\53\4\24\0\1\4\12\0\6\3\6\4\4\0"+
    "\4\4\3\0\1\4\3\0\2\4\7\0\3\4\4\0"+
    "\15\4\14\0\1\4\17\0\2\3\46\4\1\3\1\4"+
    "\5\3\1\4\2\3\53\4\1\3\115\4\1\3\4\4"+
    "\2\3\7\4\1\3\1\4\1\3\4\4\2\3\51\4"+
    "\1\3\4\4\2\3\41\4\1\3\4\4\2\3\7\4"+
    "\1\3\1\4\1\3\4\4\2\3\17\4\1\3\71\4"+
    "\1\3\4\4\2\3\103\4\2\3\3\0\40\3\20\4"+
    "\20\3\126\4\2\3\6\4\3\3\u016c\4\2\3\21\4"+
    "\1\3\32\4\5\3\113\4\3\3\13\4\7\3\22\4"+
    "\4\0\11\3\23\4\3\0\13\3\22\4\2\0\14\3"+
    "\15\4\1\3\3\4\1\3\2\0\14\3\64\4\40\0"+
    "\3\3\1\4\3\3\2\4\1\0\2\3\12\0\41\3"+
    "\17\0\6\3\131\4\7\3\5\4\2\0\42\4\1\0"+
    "\1\4\5\3\106\4\12\3\37\4\1\3\14\0\4\3"+
    "\14\0\12\3\12\0\36\4\2\3\5\4\13\3\54\4"+
    "\4\3\32\4\6\3\12\0\46\3\27\4\5\0\4\3"+
    "\65\4\12\0\1\3\35\0\2\3\13\0\6\3\12\0"+
    "\15\3\1\4\10\3\16\0\1\3\20\0\61\3\5\0"+
    "\57\4\21\0\10\4\3\3\12\0\21\3\11\0\14\3"+
    "\3\0\36\4\15\0\2\4\12\0\54\4\16\0\14\3"+
    "\44\4\24\0\10\3\12\0\3\3\3\4\12\0\44\4"+
    "\2\3\11\4\7\3\53\4\2\3\3\4\20\3\3\0"+
    "\1\3\25\0\4\4\1\0\6\4\1\0\2\4\3\0"+
    "\1\4\5\3\300\4\100\0\26\4\2\3\6\4\2\3"+
    "\46\4\2\3\6\4\2\3\10\4\1\3\1\4\1\3"+
    "\1\4\1\3\1\4\1\3\37\4\2\3\65\4\1\3"+
    "\7\4\1\3\1\4\3\3\3\4\1\3\7\4\3\3"+
    "\4\4\2\3\6\4\4\3\15\4\5\3\3\4\1\3"+
    "\7\4\16\3\5\0\30\3\2\2\5\0\20\3\2\4"+
    "\23\3\1\4\13\3\5\0\1\3\12\0\1\3\1\4"+
    "\15\3\1\4\20\3\15\4\3\3\41\4\17\3\15\0"+
    "\4\3\1\0\3\3\14\0\21\3\1\4\4\3\1\4"+
    "\2\3\12\4\1\3\1\4\3\3\5\4\6\3\1\4"+
    "\1\3\1\4\1\3\1\4\1\3\4\4\1\3\13\4"+
    "\2\3\4\4\5\3\5\4\4\3\1\4\21\3\51\4"+
    "\u0177\3\345\4\6\3\4\4\3\0\2\4\14\3\46\4"+
    "\1\3\1\4\5\3\1\4\2\3\70\4\7\3\1\4"+
    "\17\3\1\0\27\4\11\3\7\4\1\3\7\4\1\3"+
    "\7\4\1\3\7\4\1\3\7\4\1\3\7\4\1\3"+
    "\7\4\1\3\7\4\1\3\40\0\57\3\1\4\325\3"+
    "\3\4\31\3\11\4\6\0\1\3\5\4\2\3\5\4"+
    "\4\3\126\4\2\3\2\0\2\3\3\4\1\3\132\4"+
    "\1\3\4\4\5\3\53\4\1\3\136\4\21\3\40\4"+
    "\60\3\320\4\100\3\215\4\103\3\56\4\2\3\15\4"+
    "\3\3\20\4\12\0\2\4\24\3\57\4\1\0\4\3"+
    "\12\0\1\3\37\4\2\0\120\4\2\0\45\3\11\4"+
    "\2\3\147\4\2\3\100\4\5\3\2\4\1\3\1\4"+
    "\1\3\5\4\30\3\20\4\1\0\3\4\1\0\4\4"+
    "\1\0\27\4\5\0\4\3\1\0\13\3\1\4\7\3"+
    "\64\4\14\3\2\0\62\4\22\0\12\3\12\0\6\3"+
    "\22\0\6\4\3\3\1\4\1\3\2\4\13\0\34\4"+
    "\10\0\2\3\27\4\15\0\14\3\35\4\3\3\4\0"+
    "\57\4\16\0\16\3\1\4\12\0\6\3\5\4\1\0"+
    "\12\4\12\0\5\4\1\3\51\4\16\0\11\3\3\4"+
    "\1\0\10\4\2\0\2\3\12\0\6\3\27\4\3\3"+
    "\1\4\3\0\62\4\1\0\1\4\3\0\2\4\2\0"+
    "\5\4\2\0\1\4\1\0\1\4\30\3\3\4\2\3"+
    "\13\4\5\0\2\3\3\4\2\0\12\3\6\4\2\3"+
    "\6\4\2\3\6\4\11\3\7\4\1\3\7\4\1\3"+
    "\53\4\1\3\16\4\6\3\163\4\10\0\1\3\2\0"+
    "\2\3\12\0\6\3\244\4\14\3\27\4\4\3\61\4"+
    "\4\3\u0100\2\156\4\2\3\152\4\46\3\7\4\14\3"+
    "\5\4\5\3\1\4\1\0\12\4\1\3\15\4\1\3"+
    "\5\4\1\3\1\4\1\3\2\4\1\3\2\4\1\3"+
    "\154\4\41\3\153\4\22\3\100\4\2\3\66\4\50\3"+
    "\15\4\3\3\20\0\20\3\20\0\3\3\2\4\30\3"+
    "\3\4\31\3\1\4\6\3\5\4\1\3\207\4\2\3"+
    "\1\0\4\3\1\4\13\3\12\0\7\3\32\4\4\3"+
    "\1\4\1\3\32\4\13\3\131\4\3\3\6\4\2\3"+
    "\6\4\2\3\6\4\2\3\3\4\3\3\2\4\3\3"+
    "\2\4\22\3\3\0\4\3\14\4\1\3\32\4\1\3"+
    "\23\4\1\3\2\4\1\3\17\4\2\3\16\4\42\3"+
    "\173\4\105\3\65\4\210\3\1\0\202\3\35\4\3\3"+
    "\61\4\17\3\1\0\37\3\40\4\15\3\36\4\5\3"+
    "\46\4\5\0\5\3\36\4\2\3\44\4\4\3\10\4"+
    "\1\3\5\4\52\3\236\4\2\3\12\0\6\3\44\4"+
    "\4\3\44\4\4\3\50\4\10\3\64\4\14\3\13\4"+
    "\1\3\17\4\1\3\7\4\1\3\2\4\1\3\13\4"+
    "\1\3\17\4\1\3\7\4\1\3\2\4\103\3\67\4"+
    "\11\3\26\4\12\3\10\4\30\3\6\4\1\3\52\4"+
    "\1\3\11\4\105\3\6\4\2\3\1\4\1\3\54\4"+
    "\1\3\2\4\3\3\1\4\2\3\27\4\12\3\27\4"+
    "\11\3\37\4\101\3\23\4\1\3\2\4\12\3\26\4"+
    "\12\3\32\4\106\3\70\4\6\3\2\4\100\3\1\4"+
    "\3\0\1\3\2\0\5\3\4\0\4\4\1\3\3\4"+
    "\1\3\35\4\2\3\3\0\4\3\1\0\40\3\35\4"+
    "\3\3\35\4\43\3\10\4\1\3\34\4\2\0\31\3"+
    "\66\4\12\3\26\4\12\3\23\4\15\3\22\4\156\3"+
    "\111\4\67\3\63\4\15\3\63\4\15\3\44\4\4\0"+
    "\10\3\12\0\u0146\3\52\4\1\3\2\0\3\3\2\4"+
    "\113\3\3\0\35\4\12\3\1\4\10\3\26\4\13\0"+
    "\37\3\22\4\4\0\52\3\25\4\33\3\27\4\11\3"+
    "\3\0\65\4\17\0\37\3\13\0\2\4\2\0\1\4"+
    "\11\3\4\0\55\4\13\0\2\3\1\0\4\3\1\0"+
    "\12\3\1\0\2\3\31\4\7\3\12\0\6\3\3\0"+
    "\44\4\16\0\1\3\12\0\4\3\1\4\2\0\1\4"+
    "\10\3\43\4\1\0\2\3\1\4\11\3\3\0\60\4"+
    "\16\0\4\4\4\3\4\0\1\3\14\0\1\4\1\3"+
    "\1\4\43\3\22\4\1\3\31\4\14\0\6\3\1\0"+
    "\2\4\1\0\76\3\7\4\1\3\1\4\1\3\4\4"+
    "\1\3\17\4\1\3\12\4\7\3\57\4\14\0\5\3"+
    "\12\0\6\3\4\0\1\3\10\4\2\3\2\4\2\3"+
    "\26\4\1\3\7\4\1\3\2\4\1\3\5\4\1\3"+
    "\2\0\1\4\7\0\2\3\2\0\2\3\3\0\2\3"+
    "\1\4\6\3\1\0\5\3\5\4\2\0\2\3\7\0"+
    "\3\3\5\0\213\3\65\4\22\0\4\4\5\3\12\0"+
    "\4\3\1\0\3\4\36\3\60\4\24\0\2\4\1\3"+
    "\1\4\10\3\12\0\246\3\57\4\7\0\2\3\11\0"+
    "\27\3\4\4\2\0\42\3\60\4\21\0\3\3\1\4"+
    "\13\3\12\0\46\3\53\4\15\0\1\4\7\3\12\0"+
    "\66\3\33\4\2\3\17\0\4\3\12\0\6\3\7\4"+
    "\271\3\54\4\17\0\145\3\100\4\12\0\25\3\10\4"+
    "\2\3\1\4\2\3\10\4\1\3\2\4\1\3\30\4"+
    "\6\0\1\3\2\0\2\3\4\0\1\4\1\0\1\4"+
    "\2\0\14\3\12\0\106\3\10\4\2\3\47\4\7\0"+
    "\2\3\7\0\1\4\1\3\1\4\1\0\33\3\1\4"+
    "\12\0\50\4\7\0\1\4\4\0\10\3\1\0\10\3"+
    "\1\4\13\0\56\4\20\0\3\3\1\4\22\3\111\4"+
    "\7\3\11\4\1\3\45\4\10\0\1\3\10\0\1\4"+
    "\17\3\12\0\30\3\36\4\2\3\26\0\1\3\16\0"+
    "\111\3\7\4\1\3\2\4\1\3\46\4\6\0\3\3"+
    "\1\0\1\3\2\0\1\3\7\0\1\4\1\0\10\3"+
    "\12\0\6\3\6\4\1\3\2\4\1\3\40\4\5\0"+
    "\1\3\2\0\1\3\5\0\1\4\7\3\12\0\u0136\3"+
    "\23\4\4\0\11\3\2\0\1\4\1\0\15\4\1\3"+
    "\42\4\7\0\3\3\5\0\15\3\12\0\126\3\1\4"+
    "\54\3\4\4\37\3\232\4\146\3\157\4\21\3\304\4"+
    "\u014c\3\141\4\17\3\60\4\21\0\6\4\17\0\252\3"+
    "\107\4\271\3\71\4\7\3\37\4\1\3\12\0\6\3"+
    "\117\4\1\3\12\0\6\3\36\4\2\3\5\0\13\3"+
    "\60\4\7\0\11\3\4\4\14\3\12\0\11\3\25\4"+
    "\5\3\23\4\260\3\100\4\200\3\113\4\4\3\1\0"+
    "\1\4\67\0\7\3\4\0\15\4\100\3\2\4\1\3"+
    "\1\4\1\0\13\3\2\0\16\3\370\4\10\3\326\4"+
    "\52\3\11\4\u01e7\3\4\4\1\3\7\4\1\3\2\4"+
    "\1\3\43\4\17\3\1\4\35\3\3\4\2\3\1\4"+
    "\16\3\4\4\10\3\u018c\4\4\3\153\4\5\3\15\4"+
    "\3\3\11\4\7\3\12\4\3\3\2\0\1\3\4\0"+
    "\134\3\56\0\2\3\27\0\u011e\3\5\0\3\3\26\0"+
    "\2\3\7\0\36\3\4\0\224\3\3\0\273\3\125\4"+
    "\1\3\107\4\1\3\2\4\2\3\1\4\2\3\2\4"+
    "\2\3\4\4\1\3\14\4\1\3\1\4\1\3\7\4"+
    "\1\3\101\4\1\3\4\4\2\3\10\4\1\3\7\4"+
    "\1\3\34\4\1\3\4\4\1\3\5\4\1\3\1\4"+
    "\3\3\7\4\1\3\u0154\4\2\3\31\4\1\3\31\4"+
    "\1\3\37\4\1\3\31\4\1\3\37\4\1\3\31\4"+
    "\1\3\37\4\1\3\31\4\1\3\37\4\1\3\31\4"+
    "\1\3\10\4\2\3\151\0\4\3\62\0\10\3\1\0"+
    "\16\3\1\0\26\3\5\0\1\3\17\0\120\3\37\4"+
    "\6\3\6\4\325\3\7\0\1\3\21\0\2\3\7\0"+
    "\1\3\2\0\1\3\5\0\5\3\76\4\41\3\1\0"+
    "\160\3\55\4\3\3\7\0\7\4\2\3\12\0\4\3"+
    "\1\4\u0141\3\36\4\1\0\21\3\54\4\16\0\5\3"+
    "\1\4\320\3\34\4\16\0\346\3\7\4\1\3\4\4"+
    "\1\3\2\4\1\3\17\4\1\3\305\4\13\3\7\0"+
    "\51\3\104\4\7\0\1\4\4\3\12\0\u0156\3\1\4"+
    "\117\3\4\4\1\3\33\4\1\3\2\4\1\3\1\4"+
    "\2\3\1\4\1\3\12\4\1\3\4\4\1\3\1\4"+
    "\1\3\1\4\6\3\1\4\4\3\1\4\1\3\1\4"+
    "\1\3\1\4\1\3\3\4\1\3\2\4\1\3\1\4"+
    "\2\3\1\4\1\3\1\4\1\3\1\4\1\3\1\4"+
    "\1\3\1\4\1\3\2\4\1\3\1\4\2\3\4\4"+
    "\1\3\7\4\1\3\4\4\1\3\4\4\1\3\1\4"+
    "\1\3\12\4\1\3\21\4\5\3\3\4\1\3\5\4"+
    "\1\3\21\4\u0134\3\12\0\6\3\340\4\40\3\72\4"+
    "\6\3\336\4\2\3\u0182\4\16\3\u0131\4\37\3\36\4"+
    "\342\3\113\4\5\3\u0160\4\121\3\1\0\36\3\140\0"+
    "\200\3\360\0\20\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[32768];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\3\1\1\3\3"+
    "\1\15";

  private static int [] zzUnpackAction() {
    int [] result = new int[19];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\25\0\52\0\77\0\25\0\25\0\25\0\25"+
    "\0\124\0\25\0\124\0\25\0\25\0\151\0\124\0\176"+
    "\0\223\0\250\0\77";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[19];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\0\1\2\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\2\4\1\16"+
    "\2\4\1\17\27\0\1\3\23\0\1\4\3\0\1\4"+
    "\6\0\1\4\2\0\5\4\1\0\1\4\13\0\1\13"+
    "\11\0\1\4\3\0\1\4\6\0\1\4\2\0\3\4"+
    "\1\20\1\4\1\0\2\4\3\0\1\4\6\0\1\4"+
    "\2\0\1\21\4\4\1\0\2\4\3\0\1\4\6\0"+
    "\1\4\2\0\1\4\1\22\3\4\1\0\2\4\3\0"+
    "\1\4\6\0\1\4\2\0\4\4\1\23\1\0\1\4";

  private static int [] zzUnpacktrans() {
    int [] result = new int[189];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\4\11\1\1\1\11\1\1\2\11"+
    "\6\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[19];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    private TS tabla;
    public Yylex(Reader in, TS t){
        this(in);
        this.tabla = t;
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { System.out.println("Error lexico "+yytext());
            }
          // fall through
          case 14: break;
          case 2:
            { ;
            }
          // fall through
          case 15: break;
          case 3:
            { Simbolo s;
                                    if ((s = tabla.buscar(yytext()))==null)
                                        s = tabla.insertar(yytext());
                                    return new Symbol(sym.ID, s);
            }
          // fall through
          case 16: break;
          case 4:
            { return new Symbol(sym.LPAREN);
            }
          // fall through
          case 17: break;
          case 5:
            { return new Symbol(sym.RPAREN);
            }
          // fall through
          case 18: break;
          case 6:
            { return new Symbol(sym.POR);
            }
          // fall through
          case 19: break;
          case 7:
            { return new Symbol(sym.MAS);
            }
          // fall through
          case 20: break;
          case 8:
            { return new Symbol(sym.MENOS);
            }
          // fall through
          case 21: break;
          case 9:
            { return new Symbol(sym.ENTRE);
            }
          // fall through
          case 22: break;
          case 10:
            { return new Symbol(sym.NUMERO, new Integer(yytext()));
            }
          // fall through
          case 23: break;
          case 11:
            { return new Symbol(sym.PUNTOYCOMA);
            }
          // fall through
          case 24: break;
          case 12:
            { return new Symbol(sym.ASIG);
            }
          // fall through
          case 25: break;
          case 13:
            { return new Symbol(sym.PRINT);
            }
          // fall through
          case 26: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
