
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int llave_r = 42;
  public static final int switch = 9;
  public static final int using = 2;
  public static final int mul = 33;
  public static final int llave_l = 41;
  public static final int loop = 15;
  public static final int true = 25;
  public static final int do = 8;
  public static final int igual = 38;
  public static final int motors = 12;
  public static final int sensors = 13;
  public static final int boolean_type = 20;
  public static final int begin = 14;
  public static final int end = 3;
  public static final int else = 5;
  public static final int int_type = 18;
  public static final int real_type = 19;
  public static final int menos = 31;
  public static final int menor = 35;
  public static final int mayor_i = 36;
  public static final int num_real = 23;
  public static final int var = 16;
  public static final int EOF = 0;
  public static final int break = 11;
  public static final int mas = 30;
  public static final int error = 1;
  public static final int string_type = 21;
  public static final int menor_i = 37;
  public static final int mayor = 34;
  public static final int num_int = 22;
  public static final int or = 28;
  public static final int repeat = 6;
  public static final int paren_r = 40;
  public static final int while = 7;
  public static final int if = 4;
  public static final int paren_l = 39;
  public static final int corch_r = 44;
  public static final int fin = 45;
  public static final int corch_l = 43;
  public static final int false = 26;
  public static final int and = 27;
  public static final int case = 10;
  public static final int not = 29;
  public static final int div = 32;
  public static final int const = 17;
  public static final int cadena = 24;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "using",
  "end",
  "if",
  "else",
  "repeat",
  "while",
  "do",
  "switch",
  "case",
  "break",
  "motors",
  "sensors",
  "begin",
  "loop",
  "var",
  "const",
  "int_type",
  "real_type",
  "boolean_type",
  "string_type",
  "num_int",
  "num_real",
  "cadena",
  "true",
  "false",
  "and",
  "or",
  "not",
  "mas",
  "menos",
  "div",
  "mul",
  "mayor",
  "menor",
  "mayor_i",
  "menor_i",
  "igual",
  "paren_l",
  "paren_r",
  "llave_l",
  "llave_r",
  "corch_l",
  "corch_r",
  "fin"
  };
}

